/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KonversiUangTim1_ANT;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author pc
 */
public class KonversiUang extends javax.swing.JFrame {

    /**
     * Creates new form KonversiUang
     */
    public KonversiUang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tmblKeluar = new javax.swing.JButton();
        tmblKonversi = new javax.swing.JButton();
        tmblReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextJumlahUang = new javax.swing.JTextField();
        jComboBoxMenjadiUang = new javax.swing.JComboBox<>();
        jComboBoxDariUang = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextJumlahTerkonversi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tmblKeluar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tmblKeluar.setText("Keluar");
        tmblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(tmblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 330, 70));

        tmblKonversi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tmblKonversi.setText("Konversi");
        tmblKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblKonversiActionPerformed(evt);
            }
        });
        jPanel1.add(tmblKonversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 330, 70));

        tmblReset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tmblReset.setText("Reset");
        tmblReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblResetActionPerformed(evt);
            }
        });
        jPanel1.add(tmblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 330, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 1170, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 20));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 68)); // NOI18N
        jLabel2.setText("Konversi Mata Uang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1170, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 20));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setText("Dari Mata Uang");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Menjadi Mata Uang");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Jumlah Uang");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jTextJumlahUang.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jPanel3.add(jTextJumlahUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 710, 60));

        jComboBoxMenjadiUang.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jComboBoxMenjadiUang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDR - Indonesia", "USD - Dollar Amerika", "EUR - Euro", "GBP - Inggris", "JPY - Jepang", "CNY - China", "INR - India", "RUB - Rusia", "BRL - Brazil", "ZAR - Afrika Selatan", "ZMK - Zambia", "CAD - Canadian", "NGN - Nigerian", "MXN - Mexcan Peso", "CHF - Swiss Franc", "AUD - Australian" }));
        jPanel3.add(jComboBoxMenjadiUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 710, 60));

        jComboBoxDariUang.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jComboBoxDariUang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDR - Indonesia", "USD - Dollar Amerika", "EUR - Euro", "GBP - Inggris", "JPY - Jepang", "CNY - China", "INR - India", "RUB - Rusia", "BRL - Brazil", "ZAR - Afrika Selatan", "ZMK - Zambia", "CAD - Canadian", "NGN - Nigerian", "MXN - Mexcan Peso", "CHF - Swiss Franc", "AUD - Australian" }));
        jPanel3.add(jComboBoxDariUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 710, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1170, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 20));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setText("Jumlah Terkonversi");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jTextJumlahTerkonversi.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jPanel4.add(jTextJumlahTerkonversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 710, 70));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1170, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void tmblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblKeluarActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame,"Apakah anda ingin keluar?", "Currency Converter",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_tmblKeluarActionPerformed

    private void tmblKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblKonversiActionPerformed
        double amount;
    String fromCurrency;
    String toCurrency;
    double convertAmount;

    try {
        amount = Double.parseDouble(jTextJumlahUang.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid", "Eksklamasi", JOptionPane.ERROR_MESSAGE);
        jTextJumlahUang.setText("");
        jTextJumlahUang.requestFocus();
        return;
    }

    fromCurrency = jComboBoxDariUang.getSelectedItem().toString().substring(0, 3);
    toCurrency = jComboBoxMenjadiUang.getSelectedItem().toString().substring(0, 3);

    try {
        convertAmount = convertCurrency(amount, fromCurrency, toCurrency);
        jTextJumlahTerkonversi.setText(String.format("%.2f %s = %.2f %s", amount, fromCurrency, convertAmount, toCurrency));
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, "Konversi mata uang tidak valid!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tmblKonversiActionPerformed

    private void tmblResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblResetActionPerformed
        // TODO add your handling code here:
        jTextJumlahUang.setText("");
        jTextJumlahTerkonversi.setText("");
        jComboBoxDariUang.setSelectedIndex(-1);
        jComboBoxMenjadiUang.setSelectedIndex(-1);
    }//GEN-LAST:event_tmblResetActionPerformed
//------------------------------------------------------------------------------------------------------------------------
    public double convertCurrency(double amount, String fromCurrency, String toCurrency){
        Map<String, Double> conversionRate = new HashMap<>();
        conversionRate.put("GBP", 1.0);
        conversionRate.put("CAD", 1.78);
        conversionRate.put("NGN", 1674.54);
        conversionRate.put("MXN", 29.39);
        conversionRate.put("EUR", 1.35);
        conversionRate.put("CHF", 1.45);
        conversionRate.put("AUD", 1.89);
        conversionRate.put("CNY", 9.09);
        conversionRate.put("INR", 107.93);
        conversionRate.put("USD", 1.57);
        
        if(!conversionRate.containsKey(fromCurrency) || !conversionRate.containsKey(toCurrency)){
            throw new IllegalArgumentException("Invalid Currency Node");
        }
        return amount * conversionRate.get(toCurrency) / conversionRate.get(fromCurrency);
    }
//-------------------------------------------------------------------------------------------------------------------------    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiUang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDariUang;
    private javax.swing.JComboBox<String> jComboBoxMenjadiUang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextJumlahTerkonversi;
    private javax.swing.JTextField jTextJumlahUang;
    private javax.swing.JButton tmblKeluar;
    private javax.swing.JButton tmblKonversi;
    private javax.swing.JButton tmblReset;
    // End of variables declaration//GEN-END:variables
}
